all: line2ngramINT_pos

line2ngramINT_pos: line2ngramINT_pos.c *.h
	gcc -O3 line2ngramINT_pos.c -o line2ngramINT_pos

install:
	cp ./line2ngramINT_pos /home/pub/bin/
	cp ./toupper_addNO.pl /home/pub/bin/
	cp ./ngram2ngram_pair.pl /home/pub/bin/
	cp ./ngramINT_pos_pair2termVSpos_article_next.pl /home/pub/bin/
	cp ./sorted_termVSpos_article_next2reduced_list.pl /home/pub/bin/
	cp ./reduced_list2ordering.pl /home/pub/bin/
