all: ArtServer

ArtServer: *.c *.h
	gcc -Wall ArtServer.c -o ArtServer

install:
	cp ArtServer /usr/local/bin/
	cp arts.N /usr/local/var/arts/
	cp arts.idx /usr/local/var/arts/
	cp arts.conf /usr/local/var/arts/
